spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true